name: Build Mobywatel IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CocoaPods
      run: cd mobywatel && pod install
    - name: Build Mobywatel Archive
      run: xcodebuild -workspace Mobywatel/mobywatel.xcworkspace -scheme Mobywatel -sdk iphoneos -configuration Release -archivePath build.xcarchive archive CODE_SIGNING_ALLOWED=NO
    - name: Export Mobywatel IPA
      run: |
        mkdir Payload
        cp -r build.xcarchive/Products/Applications/mobywatel.app Payload/
        zip -r Mobywatel.ipa Payload/
    - name: Upload Mobywatel IPA
      uses: actions/upload-artifact@v4
      with:
        name: mobywatel-IPA
        path: mobywatel.ipa
